import Head from "next/head";
import Navbar from "../components/navbar";
import Department from "../components/Department";
import VideoPlayer from "../components/VideoPlayer";
import Course from "../components/Course";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vir-Uni Yashodhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=1440" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <section className="mx-auto bg-[url('/background/section1.png')] bg-no-repeat bg-contain w-[1400px] h-[640px]">
          <div className="w-1/3 mx-24 my-24 space-y-4">
            <p className="text-4xl text-orange-600 font-bold">
              Innovation for Education and Society
            </p>
            <p className="text-lg text-gray-600 pb-4">
              Our interdisciplinary majors and minors mean you can chart your
              own course for academic success.
            </p>

            <button className="text-white text-lg py-4 px-8 bg-orange-600 hover:bg-white hover:border-orange-600 hover:border hover:text-orange-600 rounded-full">
              Visit our Campus
            </button>
          </div>
        </section>

        <section className="w-2/3 mx-auto">
          <div className="my-20">
            <p className="text-4xl text-center font-bold text-black mb-4 hover:text-orange-600">
              Our Department
            </p>
            <p className="text-gray-600 text-center text-lg">
              A hundred thousand grateful loves to your dear papa and mamma. Is
              your poor brother recovered of his rack-punch? Oh, dear! Oh, dear!
              How men should beware of wicked punch!
            </p>
          </div>

          <div className="flex items-center justify-center gap-12 my-12">
            <Department
              imagePath="/departments/bg3.png"
              backgroundColor="bg-[#ffb258] orange"
              title="Online Education"
            />
            <Department
              imagePath="/departments/bg2.png"
              backgroundColor="bg-[#80be41]"
              title="Online Education"
            />
            <Department
              imagePath="/departments/BG.png"
              backgroundColor="bg-[#f9703a]"
              title="Online Education"
            />
          </div>
        </section>

        <section className="flex items-center justify-around my-24 mx-auto">
          <VideoPlayer />

          <div className="flex-col items-center h-auto space-y-12 w-[500px] ">
            <p className="text-4xl text-black font-bold hover:text-orange-600">
              Limitless learning, More possibilities
            </p>
            <p className="text-lg text-gray-600">
              The University of Rochester is one of the countrys top-tier
              research universities. Our campuses are home to 200 academic
              majors, more than 2,000 faculty and instructional staff, and some
              10,000 students—approximately half of whom are women. Learning at
              the University of Rochester is also on a very personal scale.
              Rochester remains one of the smallest and most collegiate among
              top research universities, with smaller classes, a low 10:1
              student to teacher ratio, and increased interactions with faculty.
            </p>

            <div className="flex items-center justfy-between gap-16 mt-6">
              <p className="text-yellow-600 text-2xl font-bold">
                4000
                <p className="text-yellow-600 text-xl font-thin">Students</p>
              </p>

              <p className="text-red-600 text-2xl font-bold">
                260 <p className="text-red-600 text-xl font-thin">Courses</p>
              </p>
              <p className="text-green-600 text-2xl font-bold">
                5679{" "}
                <p className="text-green-600 text-xl font-thin">Hours Video</p>
              </p>
            </div>
          </div>
        </section>

        <section>
          <p className="text-4xl text-black font-bold text-center hover:text-orange-600">
            Around the University
          </p>

          <div className="flex items-center justify-center">
            <div className="grid grid-cols-4 gap-12 grid-rows-2 my-12">
              <Course
                imagePath="/courses/one.png"
                title="Photoshop CC 2018 Essential 
Training: The Basics"
                type="Graphics Design"
              />

              <Course
                imagePath="/courses/two.png"
                title="Get Started Coding Android 
              Apps With Kotlin"
                type="Global System"
              />

              <Course
                imagePath="/courses/three.png"
                title="Create Turntable Animations 
              With Cinema 4D"
                type="Computer & Information Technology"
              />

              <Course
                imagePath="/courses/one.png"
                title="Photoshop CC 2018 Essential 
Training: The Basics"
                type="Graphics Design"
              />

              <Course
                imagePath="/courses/two.png"
                title="Get Started Coding Android 
              Apps With Kotlin"
                type="Global System"
              />

              <Course
                imagePath="/courses/three.png"
                title="Create Turntable Animations 
              With Cinema 4D"
                type="Computer & Information Technology"
              />
              <Course
                imagePath="/courses/one.png"
                title="Photoshop CC 2018 Essential 
Training: The Basics"
                type="Graphics Design"
              />

              <Course
                imagePath="/courses/two.png"
                title="Get Started Coding Android 
              Apps With Kotlin"
                type="Global System"
              />
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
